name: "Lint (Using Super-linter)"

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  dothejob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: RUn the Super-Linter
        uses: github/super-linter@v4.8.1
